/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/model/gaming_room.glb
Author: Indvisible (https://sketchfab.com/indvisible)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gaming-room-3d0c90d37a0b429c848f92deacdb869e
Title: Gaming Room
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function RoomModel2(props) {
  const { nodes, materials } = useGLTF('./model/gaming_room.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-8.98, 14.68, 10.03]} rotation={[3.03, 0, Math.PI]} scale={18.15}>
        <mesh geometry={nodes.Object_22.geometry} material={materials['Material.022']} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.Screen} />
      </group>
      <group position={[10.52, 15.66, -14.57]}>
        <mesh geometry={nodes.Object_25.geometry} material={materials['Material.021']} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.Nikon} />
      </group>
      <group position={[10.89, 13.62, 9.9]} rotation={[0, 0.01, 0]} scale={[14.24, 14.24, 12.27]}>
        <group position={[-0.02, 0.1, 0]} rotation={[1.57, -0.1, -1.57]} scale={1.05}>
          <mesh geometry={nodes.Object_31.geometry} material={materials.book_cover} />
          <mesh geometry={nodes.Object_32.geometry} material={materials.stacked_paper} />
        </group>
        <group position={[-0.06, 0.12, -0.01]} rotation={[1.57, -0.11, -1.57]} scale={1.05}>
          <mesh geometry={nodes.Object_34.geometry} material={materials.book_cover} />
          <mesh geometry={nodes.Object_35.geometry} material={materials.stacked_paper} />
        </group>
        <group position={[-0.05, 0.12, -0.01]} rotation={[1.57, -0.11, -1.57]} scale={1.05}>
          <mesh geometry={nodes.Object_37.geometry} material={materials.book_cover} />
          <mesh geometry={nodes.Object_38.geometry} material={materials.stacked_paper} />
        </group>
        <group position={[-0.03, 0.1, 0]} rotation={[1.57, -0.11, -1.57]} scale={1.05}>
          <mesh geometry={nodes.Object_40.geometry} material={materials.book_cover} />
          <mesh geometry={nodes.Object_41.geometry} material={materials.stacked_paper} />
        </group>
        <group position={[-0.09, 0.09, 0]} rotation={[1.57, -0.15, -1.57]} scale={1.05}>
          <mesh geometry={nodes.Object_43.geometry} material={materials.book_cover} />
          <mesh geometry={nodes.Object_44.geometry} material={materials.stacked_paper} />
        </group>
        <group position={[-0.11, 0.12, -0.01]} rotation={[1.57, -0.2, -1.57]} scale={1.05}>
          <mesh geometry={nodes.Object_46.geometry} material={materials.book_cover} />
          <mesh geometry={nodes.Object_47.geometry} material={materials.stacked_paper} />
        </group>
        <group position={[-0.13, 0.12, -0.01]} rotation={[1.57, -0.2, -1.57]} scale={1.05}>
          <mesh geometry={nodes.Object_49.geometry} material={materials.book_cover} />
          <mesh geometry={nodes.Object_50.geometry} material={materials.stacked_paper} />
        </group>
        <group position={[-0.25, 0.12, 0]} rotation={[1.57, -0.22, -1.57]} scale={1.05}>
          <mesh geometry={nodes.Object_52.geometry} material={materials.book_cover} />
          <mesh geometry={nodes.Object_53.geometry} material={materials.stacked_paper} />
        </group>
        <group position={[-0.23, 0.12, -0.01]} rotation={[1.57, -0.21, -1.57]} scale={1.05}>
          <mesh geometry={nodes.Object_55.geometry} material={materials.book_cover} />
          <mesh geometry={nodes.Object_56.geometry} material={materials.stacked_paper} />
        </group>
        <group position={[-0.22, 0.09, 0]} rotation={[1.57, -0.21, -1.57]} scale={1.05}>
          <mesh geometry={nodes.Object_58.geometry} material={materials.book_cover} />
          <mesh geometry={nodes.Object_59.geometry} material={materials.stacked_paper} />
        </group>
        <group position={[-0.16, 0.1, -0.01]} rotation={[1.57, -0.2, -1.57]} scale={1.05}>
          <mesh geometry={nodes.Object_61.geometry} material={materials.book_cover} />
          <mesh geometry={nodes.Object_62.geometry} material={materials.stacked_paper} />
        </group>
        <group position={[-0.17, 0.12, -0.01]} rotation={[1.57, -0.21, -1.57]} scale={1.05}>
          <mesh geometry={nodes.Object_64.geometry} material={materials.book_cover} />
          <mesh geometry={nodes.Object_65.geometry} material={materials.stacked_paper} />
        </group>
        <group position={[-0.19, 0.12, 0]} rotation={[1.57, -0.21, -1.57]} scale={1.05}>
          <mesh geometry={nodes.Object_67.geometry} material={materials.book_cover} />
          <mesh geometry={nodes.Object_68.geometry} material={materials.stacked_paper} />
        </group>
        <group position={[-0.14, 0.1, -0.01]} rotation={[1.57, -0.2, -1.57]} scale={1.05}>
          <mesh geometry={nodes.Object_70.geometry} material={materials.book_cover} />
          <mesh geometry={nodes.Object_71.geometry} material={materials.stacked_paper} />
        </group>
        <group position={[-0.27, 0.1, 0]} rotation={[1.57, -0.22, -1.57]}>
          <mesh geometry={nodes.Object_73.geometry} material={materials.book_cover} />
          <mesh geometry={nodes.Object_74.geometry} material={materials.stacked_paper} />
        </group>
        <group position={[-0.31, 0.11, 0]} rotation={[1.57, -0.22, -1.58]}>
          <mesh geometry={nodes.Object_76.geometry} material={materials.book_cover} />
          <mesh geometry={nodes.Object_77.geometry} material={materials.stacked_paper} />
        </group>
        <group position={[-0.29, 0.12, 0]} rotation={[1.57, -0.22, -1.57]}>
          <mesh geometry={nodes.Object_79.geometry} material={materials.book_cover} />
          <mesh geometry={nodes.Object_80.geometry} material={materials.stacked_paper} />
        </group>
        <group position={[-0.28, 0.1, 0.01]} rotation={[1.57, -0.22, -1.57]}>
          <mesh geometry={nodes.Object_82.geometry} material={materials.book_cover} />
          <mesh geometry={nodes.Object_83.geometry} material={materials.stacked_paper} />
        </group>
        <group position={[-0.35, 0.09, 0.01]} rotation={[1.57, -0.32, -1.58]}>
          <mesh geometry={nodes.Object_85.geometry} material={materials.book_cover} />
          <mesh geometry={nodes.Object_86.geometry} material={materials.stacked_paper} />
        </group>
        <group position={[-0.37, 0.11, -0.01]} rotation={[1.57, -0.43, -1.57]}>
          <mesh geometry={nodes.Object_88.geometry} material={materials.book_cover} />
          <mesh geometry={nodes.Object_89.geometry} material={materials.stacked_paper} />
        </group>
        <group position={[-0.39, 0.11, -0.01]} rotation={[1.57, -0.45, -1.57]}>
          <mesh geometry={nodes.Object_91.geometry} material={materials.book_cover} />
          <mesh geometry={nodes.Object_92.geometry} material={materials.stacked_paper} />
        </group>
      </group>
      <group position={[-0.39, 0.11, 0.02]} rotation={[1.57, -0.45, -1.57]}>
        <mesh geometry={nodes.Object_94.geometry} material={materials.book_cover} />
        <mesh geometry={nodes.Object_95.geometry} material={materials.stacked_paper} />
      </group>
      <group position={[-0.37, 0.11, 0.02]} rotation={[1.57, -0.43, -1.57]}>
        <mesh geometry={nodes.Object_97.geometry} material={materials.book_cover} />
        <mesh geometry={nodes.Object_98.geometry} material={materials.stacked_paper} />
      </group>
      <group position={[-0.35, 0.09, 0.03]} rotation={[1.57, -0.32, -1.58]}>
        <mesh geometry={nodes.Object_100.geometry} material={materials.book_cover} />
        <mesh geometry={nodes.Object_101.geometry} material={materials.stacked_paper} />
      </group>
      <group position={[-0.29, 0.1, 0.03]} rotation={[1.57, -0.22, -1.57]}>
        <mesh geometry={nodes.Object_103.geometry} material={materials.book_cover} />
        <mesh geometry={nodes.Object_104.geometry} material={materials.stacked_paper} />
      </group>
      <group position={[-0.3, 0.12, 0.02]} rotation={[1.57, -0.22, -1.57]}>
        <mesh geometry={nodes.Object_106.geometry} material={materials.book_cover} />
        <mesh geometry={nodes.Object_107.geometry} material={materials.stacked_paper} />
      </group>
      <group position={[-0.31, 0.11, 0.02]} rotation={[1.57, -0.22, -1.58]}>
        <mesh geometry={nodes.Object_109.geometry} material={materials.book_cover} />
        <mesh geometry={nodes.Object_110.geometry} material={materials.stacked_paper} />
      </group>
      <group position={[-0.27, 0.1, 0.02]} rotation={[1.57, -0.22, -1.57]}>
        <mesh geometry={nodes.Object_112.geometry} material={materials.book_cover} />
        <mesh geometry={nodes.Object_113.geometry} material={materials.stacked_paper} />
      </group>
      <group position={[-0.15, 0.1, 0.02]} rotation={[1.57, -0.2, -1.57]} scale={1.05}>
        <mesh geometry={nodes.Object_115.geometry} material={materials.book_cover} />
        <mesh geometry={nodes.Object_116.geometry} material={materials.stacked_paper} />
      </group>
      <group position={[-0.19, 0.12, 0.02]} rotation={[1.57, -0.21, -1.57]} scale={1.05}>
        <mesh geometry={nodes.Object_118.geometry} material={materials.book_cover} />
        <mesh geometry={nodes.Object_119.geometry} material={materials.stacked_paper} />
      </group>
      <group position={[-0.18, 0.12, 0.02]} rotation={[1.57, -0.21, -1.57]} scale={1.05}>
        <mesh geometry={nodes.Object_121.geometry} material={materials.book_cover} />
        <mesh geometry={nodes.Object_122.geometry} material={materials.stacked_paper} />
      </group>
      <group position={[-0.16, 0.1, 0.01]} rotation={[1.57, -0.2, -1.57]} scale={1.05}>
        <mesh geometry={nodes.Object_124.geometry} material={materials.book_cover} />
        <mesh geometry={nodes.Object_125.geometry} material={materials.stacked_paper} />
      </group>
      <group position={[-0.22, 0.09, 0.02]} rotation={[1.57, -0.21, -1.57]} scale={1.05}>
        <mesh geometry={nodes.Object_127.geometry} material={materials.book_cover} />
        <mesh geometry={nodes.Object_128.geometry} material={materials.stacked_paper} />
      </group>
      <group position={[-0.23, 0.12, 0.01]} rotation={[1.57, -0.21, -1.57]} scale={1.05}>
        <mesh geometry={nodes.Object_130.geometry} material={materials.book_cover} />
        <mesh geometry={nodes.Object_131.geometry} material={materials.stacked_paper} />
      </group>
      <group position={[-0.25, 0.12, 0.02]} rotation={[1.57, -0.22, -1.57]} scale={1.05}>
        <mesh geometry={nodes.Object_133.geometry} material={materials.book_cover} />
        <mesh geometry={nodes.Object_134.geometry} material={materials.stacked_paper} />
      </group>
      <group position={[-0.13, 0.12, 0.02]} rotation={[1.57, -0.2, -1.57]} scale={1.05}>
        <mesh geometry={nodes.Object_136.geometry} material={materials.book_cover} />
        <mesh geometry={nodes.Object_137.geometry} material={materials.stacked_paper} />
      </group>
      <group position={[-0.11, 0.12, 0.02]} rotation={[1.57, -0.2, -1.57]} scale={1.05}>
        <mesh geometry={nodes.Object_139.geometry} material={materials.book_cover} />
        <mesh geometry={nodes.Object_140.geometry} material={materials.stacked_paper} />
      </group>
      <group position={[-0.1, 0.09, 0.02]} rotation={[1.57, -0.15, -1.57]} scale={1.05}>
        <mesh geometry={nodes.Object_142.geometry} material={materials.book_cover} />
        <mesh geometry={nodes.Object_143.geometry} material={materials.stacked_paper} />
      </group>
      <group position={[-0.04, 0.1, 0.03]} rotation={[1.57, -0.11, -1.57]} scale={1.05}>
        <mesh geometry={nodes.Object_145.geometry} material={materials.book_cover} />
        <mesh geometry={nodes.Object_146.geometry} material={materials.stacked_paper} />
      </group>
      <group position={[-0.05, 0.12, 0.01]} rotation={[1.57, -0.11, -1.57]} scale={1.05}>
        <mesh geometry={nodes.Object_148.geometry} material={materials.book_cover} />
        <mesh geometry={nodes.Object_149.geometry} material={materials.stacked_paper} />
      </group>
      <group position={[-0.07, 0.12, 0.02]} rotation={[1.57, -0.11, -1.57]} scale={1.05}>
        <mesh geometry={nodes.Object_151.geometry} material={materials.book_cover} />
        <mesh geometry={nodes.Object_152.geometry} material={materials.stacked_paper} />
      </group>
      <group position={[-0.02, 0.1, 0.02]} rotation={[1.57, -0.1, -1.57]} scale={1.05}>
        <mesh geometry={nodes.Object_154.geometry} material={materials.book_cover} />
        <mesh geometry={nodes.Object_155.geometry} material={materials.stacked_paper} />
      </group>
      <group position={[2.76, 13.63, 9.95]} rotation={[-0.01, 0, 0]} scale={9.81}>
        <mesh geometry={nodes.Object_164.geometry} material={materials['Material.020']} position={[0.02, 0.15, 0]} />
        <mesh geometry={nodes.Object_166.geometry} material={materials['Material.020']} position={[0.01, 0.15, -0.01]} />
        <mesh geometry={nodes.Object_168.geometry} material={materials['Material.020']} position={[0.01, 0.12, 0.02]} />
        <mesh geometry={nodes.Object_170.geometry} material={materials['Material.020']} position={[-0.02, 0.15, -0.01]} />
        <mesh geometry={nodes.Object_172.geometry} material={materials['Material.020']} position={[-0.01, 0.15, 0.02]} />
        <mesh geometry={nodes.Object_174.geometry} material={materials['Material.020']} position={[0.03, 0.18, 0]} />
        <mesh geometry={nodes.Object_176.geometry} material={materials['Material.020']} position={[0.01, 0.09, 0.02]} />
        <mesh geometry={nodes.Object_178.geometry} material={materials['Material.020']} position={[-0.02, 0.16, 0]} />
        <mesh geometry={nodes.Object_180.geometry} material={materials['Material.020']} position={[0.03, 0.06, -0.02]} />
        <mesh geometry={nodes.Object_182.geometry} material={materials['Material.020']} position={[0.05, 0.24, 0.01]} />
        <mesh geometry={nodes.Object_184.geometry} material={materials['Material.020']} position={[0.01, 0.21, -0.04]} />
        <mesh geometry={nodes.Object_186.geometry} material={materials['Material.020']} position={[-0.01, 0.21, 0.04]} />
        <mesh geometry={nodes.Object_188.geometry} material={materials['Material.020']} position={[0, 0.05, -0.01]} />
        <mesh geometry={nodes.Object_190.geometry} material={materials['Material.020']} position={[0.01, 0.21, 0.02]} />
        <mesh geometry={nodes.Object_192.geometry} material={materials['Material.020']} position={[0.02, 0.16, 0]} />
        <mesh geometry={nodes.Object_194.geometry} material={materials['Material.020']} position={[-0.01, 0.19, 0]} />
        <mesh geometry={nodes.Object_196.geometry} material={materials['Material.020']} position={[-0.01, 0.34, 0.02]} />
        <mesh geometry={nodes.Object_198.geometry} material={materials['Material.019']} position={[0, 0.08, 0]} />
        <mesh geometry={nodes.Object_200.geometry} material={materials['Material.020']} position={[0.09, 0.28, -0.04]} />
        <mesh geometry={nodes.Object_202.geometry} material={materials['Material.020']} position={[-0.03, 0.27, -0.07]} />
        <mesh geometry={nodes.Object_204.geometry} material={materials['Material.020']} position={[0.06, 0.38, 0.01]} />
        <mesh geometry={nodes.Object_206.geometry} material={materials['Material.020']} position={[0.02, 0.31, -0.03]} />
        <mesh geometry={nodes.Object_208.geometry} material={materials['Material.020']} position={[0.02, 0.3, -0.03]} />
        <mesh geometry={nodes.Object_210.geometry} material={materials['Material.020']} position={[0.06, 0.37, 0.02]} />
        <mesh geometry={nodes.Object_212.geometry} material={materials['Material.020']} position={[0.01, 0.37, 0.03]} />
        <mesh geometry={nodes.Object_214.geometry} material={materials['Material.020']} position={[0.01, 0.37, 0.03]} />
        <mesh geometry={nodes.Object_216.geometry} material={materials['Material.020']} position={[-0.02, 0.36, -0.01]} />
        <mesh geometry={nodes.Object_218.geometry} material={materials['Material.020']} position={[-0.02, 0.36, -0.01]} />
        <mesh geometry={nodes.Object_220.geometry} material={materials['Material.020']} position={[0, 0.24, -0.02]} />
        <mesh geometry={nodes.Object_222.geometry} material={materials['Material.020']} position={[0.04, 0.3, 0.08]} />
        <mesh geometry={nodes.Object_224.geometry} material={materials['Material.020']} position={[0.04, 0.3, 0.07]} />
        <mesh geometry={nodes.Object_226.geometry} material={materials['Material.020']} position={[-0.02, 0.23, 0.01]} />
        <mesh geometry={nodes.Object_228.geometry} material={materials['Material.020']} position={[0.03, 0.36, 0]} />
        <mesh geometry={nodes.Object_230.geometry} material={materials['Material.020']} position={[-0.01, 0.23, 0.01]} />
        <mesh geometry={nodes.Object_232.geometry} material={materials['Material.020']} position={[0.03, 0.36, 0]} />
        <mesh geometry={nodes.Object_234.geometry} material={materials['Material.020']} position={[0.1, 0.34, 0.02]} />
        <mesh geometry={nodes.Object_236.geometry} material={materials['Material.020']} position={[0.09, 0.34, 0.02]} />
        <mesh geometry={nodes.Object_238.geometry} material={materials['Material.020']} position={[0.02, 0.21, -0.02]} />
        <mesh geometry={nodes.Object_240.geometry} material={materials['Material.020']} position={[-0.03, 0.31, 0.09]} />
        <mesh geometry={nodes.Object_242.geometry} material={materials['Material.020']} position={[-0.03, 0.31, 0.08]} />
        <mesh geometry={nodes.Object_244.geometry} material={materials['Material.020']} position={[0.01, 0.32, 0.02]} />
        <mesh geometry={nodes.Object_246.geometry} material={materials['Material.020']} position={[0.01, 0.32, 0.02]} />
        <mesh geometry={nodes.Object_248.geometry} material={materials['Material.020']} position={[0, 0.35, -0.01]} />
        <mesh geometry={nodes.Object_250.geometry} material={materials['Material.020']} position={[0, 0.34, -0.01]} />
        <mesh geometry={nodes.Object_252.geometry} material={materials['Material.020']} position={[-0.04, 0.34, 0]} />
        <mesh geometry={nodes.Object_254.geometry} material={materials['Material.020']} position={[-0.04, 0.33, 0]} />
        <mesh geometry={nodes.Object_256.geometry} material={materials['Material.020']} position={[0, 0.31, -0.08]} />
        <mesh geometry={nodes.Object_258.geometry} material={materials['Material.020']} position={[0, 0.31, -0.08]} />
        <mesh geometry={nodes.Object_260.geometry} material={materials['Material.020']} position={[0.01, 0.22, 0.02]} />
        <mesh geometry={nodes.Object_262.geometry} material={materials['Material.020']} position={[0, 0.23, -0.01]} />
        <mesh geometry={nodes.Object_264.geometry} material={materials['Material.020']} position={[-0.05, 0.29, 0.04]} />
        <mesh geometry={nodes.Object_266.geometry} material={materials['Material.020']} position={[-0.05, 0.29, 0.03]} />
      </group>
      <group position={[-8.22, 6.22, 7.14]} rotation={[3.06, -1.57, -Math.PI]} scale={[0.21, 0.11, 0.21]}>
        <mesh geometry={nodes.Object_270.geometry} material={materials.Basic_Glass} />
        <mesh geometry={nodes.Object_271.geometry} material={materials['Material.015']} />
      </group>
      <group position={[-5.01, 8.38, 9.09]} rotation={[-Math.PI, -0.17, -Math.PI]} scale={9.34}>
        <mesh geometry={nodes.Object_287.geometry} material={materials['Material.023']} />
        <mesh geometry={nodes.Object_288.geometry} material={materials.Screen} />
      </group>
      <group position={[-10.63, 8.38, 9.1]} rotation={[-Math.PI, 0.17, -Math.PI]} scale={9.34}>
        <mesh geometry={nodes.Object_290.geometry} material={materials['Material.024']} />
        <mesh geometry={nodes.Object_291.geometry} material={materials.Screen} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.016']} position={[5.77, 4.37, -0.44]} scale={[5.77, 8.27, 6.29]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['Material.002']} position={[5.93, 2.53, -0.1]} scale={4.28} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['Material.016']} position={[-6.01, 5.57, 8.31]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials['Material.014']} position={[6.31, 5.9, 6.55]} rotation={[2.95, 0, 0]} scale={[-13.68, 1.87, 18.74]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.Leather_blue} position={[6.01, 5.35, -2.48]} scale={[8.05, 7.24, 8.92]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials['Material.003']} position={[8.96, 7.51, -17.41]} rotation={[-Math.PI, -0.02, -Math.PI]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials['Material.003']} position={[5.84, 11.37, 9.46]} rotation={[0, Math.PI / 2, 0]} scale={0.77} />
      <mesh geometry={nodes.Object_18.geometry} material={materials['Material.016']} position={[-10.9, 1.82, -12.22]} scale={[0.86, 1, 1.12]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.Screen} position={[-9.5, 3.98, -13.34]} scale={[5.07, 5.89, 6.6]} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.material_0} position={[-17.04, 7.69, 15.73]} scale={0.77} />
      <mesh geometry={nodes.Object_157.geometry} material={materials.Screen} position={[-0.58, 8.51, 8.26]} scale={[0.92, 1.17, 1.17]} />
      <mesh geometry={nodes.Object_159.geometry} material={materials.material_0} position={[0.13, 8.09, 5.95]} scale={1.17} />
      <mesh geometry={nodes.Object_161.geometry} material={materials.material_0} position={[-0.6, 8.65, 5.67]} rotation={[Math.PI / 2, 0, 0]} scale={0.12} />
      <mesh geometry={nodes.Object_268.geometry} material={materials.BlackPlastic} position={[-5.65, 6.23, 7.49]} rotation={[3.06, -1.57, -Math.PI]} scale={[1.16, 0.14, 3.19]} />
      <mesh geometry={nodes.Object_273.geometry} material={materials['Material.009']} position={[-7.78, 6.01, 7.19]} />
      <mesh geometry={nodes.Object_275.geometry} material={materials.Screen} position={[-7.59, 5.71, 1.19]} rotation={[0, -0.28, 0]} scale={2.1} />
      <mesh geometry={nodes.Object_277.geometry} material={materials.Leather_blue} position={[-5.56, 4.54, 2.39]} rotation={[0, -0.28, 0]} scale={[2.04, 2.14, 2.14]} />
      <mesh geometry={nodes.Object_279.geometry} material={materials.Screen} position={[-7.66, 5.74, 1.18]} rotation={[0, -0.28, 0]} scale={2.1} />
      <mesh geometry={nodes.Object_281.geometry} material={materials.Screen} position={[-3.13, 5.74, 2.5]} rotation={[0, -0.28, 0]} scale={[-2.1, 2.1, 2.1]} />
      <mesh geometry={nodes.Object_283.geometry} material={materials.Screen} position={[-5.54, 1.1, 2.25]} rotation={[0, -0.28, 0]} scale={[1.53, 0.51, 1.53]} />
      <mesh geometry={nodes.Object_285.geometry} material={materials.Screen} position={[-5.54, 2.07, 2.25]} rotation={[0, -0.28, 0]} scale={[1.17, 0.57, 1.17]} />
      <mesh geometry={nodes.Object_293.geometry} material={materials.Material} />
      <mesh geometry={nodes.Object_295.geometry} material={materials.Nikon} position={[11.7, 12.7, 0.74]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_297.geometry} material={materials.Nikon} position={[-16.29, 12.72, 17.23]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Object_299.geometry} material={materials['Material.002']} position={[10.18, 1.58, 0.64]} />
      <mesh geometry={nodes.Object_301.geometry} material={materials['Material.016']} position={[-16.42, 6.83, 18.31]} rotation={[0, -Math.PI / 2, 0]} scale={3.94} />
      <mesh geometry={nodes.Object_303.geometry} material={materials.Screen} position={[10.98, 17.26, -3.71]} rotation={[Math.PI / 2, 0, 0]} scale={[2.14, 1.49, 2.14]} />
      <mesh geometry={nodes.Object_305.geometry} material={materials.Leather_blue} position={[10.43, 12.68, 1.05]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[1.82, 6.58, 1.8]} />
      <mesh geometry={nodes.Object_307.geometry} material={materials.Leather_blue} position={[10.47, 11.9, -7.29]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[1.83, 4.37, 1.83]} />
      <mesh geometry={nodes.Object_309.geometry} material={materials.material_0} position={[11.25, 11.16, -1.78]} scale={[0.83, 1, 1]} />
      <mesh geometry={nodes.Object_311.geometry} material={materials.material_0} position={[11.46, 11.16, -1.78]} scale={[0.83, 1, 1]} />
      <mesh geometry={nodes.Object_313.geometry} material={materials['Material.018']} position={[0, -4.45, 0]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./model/gaming_room.glb')
